apiVersion: v1
kind: PersistentVolume
metadata:
  name: feedback-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data/feedback-db"