apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feedback-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      type: local