apiVersion: v1
kind: Service
metadata:
  name: logic-api-svc
  labels:
    app: logic-api
spec:
  type: ClusterIP
  selector:
    app: logic-api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000